# 1. 站点基础信息 (Site Information)
site_name: 陈闻天的个人博客
site_description: 记录具身智能研究、机器人项目与技术博客
site_author: Wentian Chen
site_url: https://bluejade115.github.io/WentianChen.github.io/
# 2. 主题与功能配置 (Theme Configuration)
theme:
  name: material
  language: zh # 设置语言为中文，优化搜索分词和界面提示
  features:
    - search.suggest       # 搜索输入时显示补全建议
    - search.highlight     # 搜索结果高亮显示
    - navigation.tabs      # 顶部显示一级导航栏
    - navigation.top       # 开启“回到顶部”按钮（文章长时非常实用）
    - toc.follow           # 右侧目录高亮会跟随你在文章中的滚动自动切换
    - content.code.copy    # 允许一键复制你的代码块

# 3. 网站导航目录结构 (Navigation Structure)
nav:
  - 首页: index.md
  - 个人简历: resume.md
  - 项目展示:
    - test: projects/text.md
    - 基于IsaacSim的CuRobo自动抓取及数据采集: projects/simpickgen.md
  - 教程博客:
    - 博客首页: blog/index.md
    - 环境配置:
      - 常见Linux小问题的解决方法: blog/envir_config/fix_some_common_linux_bugs.md
      - 配置国内APT镜像源: blog/envir_config/config_apt.md
      - 配置Pip: blog/envir_config/config_pip.md
      - 配置NVIDIA Driver: blog/envir_config/config_nvidia_driver.md
      - 配置CUDA: blog/envir_config/config_cuda.md
      - 配置SSH: blog/envir_config/config_ssh.md
      - 配置Docker: blog/envir_config/config_docker.md
    - ROS:
      - 配置ROS: blog/ros/config_ros.md
      - ROS2的深入理解: blog/ros/dive_into_ros2.md
      - SLAM和Navigation: blog/ros/slam_and_navigation.md
      - CMakelists详解: blog/ros/cmakelists_guide.md
    - Computer Vision:
      - Yolo的全流程指南: blog/cv/yolo_guide.md
    - 大模型:
      - pytorch: blog/model/dive_into_pytorch.md
